project_name: test-goreleaser
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["ghcr.io/justinharringa/test-goreleaser:{{ .Version }}"]
  use: buildpacks
nfpms:
- maintainer: Justin Harringa <justin@harringa.com>
  description: Sample project.
  homepage: https://github.com/justinharringa/test-goreleaser
  license: MIT
  formats:
  - deb
  - rpm
  - apk
